version: "3.2"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
